[workspace]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
name = "data-science-at-the-command-line"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.2,<4.6"
r-bookdown = ">=0.46,<0.47"
r-downlit = ">=0.4.5,<0.5"
r-xml2 = ">=1.5.2,<2"
pandoc = ">=3.8.3,<4"
make = ">=4.4.1,<5"
python = ">=3.14.2,<3.15"
pandocfilters = ">=1.5.0,<2"
ansi2html = ">=1.9.2,<2"
